const ActionName = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  USER: "USER",
  ALL_USER: "ALL_USER",
  LOADING: "loading",


  //Content API's
  GET_ALL_CONTENT: "GET_ALL_CONTENT",
  GET_CONTENT_BY_ID: "GET_CONTENT_BY_ID",
  UPDATE_CONTENT: "UPDATE_CONTENT",
  IMPORT_CONTENT: "IMPORT_CONTENT",
  EXPORT_CONTENT: "EXPORT_CONTENT",
  GET_CONTENT_LANGUAGE: "GET_CONTENT_LANGUAGE",
  GET_CONTENT_TRANSLATION: "GET_CONTENT_TRANSLATION",
  POST_CONTENT_TRANSLATION: "POST_CONTENT_TRANSLATION",

 
};

export default ActionName;
